name: RadiationZones
version: '${version}'
main: pl.fuzjajadrowa.radiationzones.RadiationZones
api-version: '1.21'
load: STARTUP
authors: [FuzjaJadrowa]
description: Radiation Zones adds configurable radiation zones to Minecraft. Players outside safe areas receive harmful effects unless protected by Lugol's iodine.
website: https://fuzjajadrowa.pl

commands:
  radiation:
    description: Plugin commands.
    permission: radiationzones.radiation
    usage: /radiation <safe <radius>|clear|potion <identifier>>

permissions:
  radiationzones.*:
    description: Gives all possible permissions.
    default: false
    children:
      radiationzones.radiation: true
      radiationzones.admin: true
  radiationzones.admin:
    description: Gives access to admin notifications.
    default: op
  radiationzones.radiation:
    description: Gives access to the /radiation command.
    default: op