modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
logoFile="assets/radiationzones/textures/icon.png"
authors="${mod_author}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"